# Generated by Django 2.2.16 on 2022-01-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='created',
        ),
    ]
