# Generated by Django 2.2.16 on 2022-01-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_follow_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
