# Generated by Django 2.2.16 on 2022-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220205_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(default='Автор еще не заполнил этот раздел', max_length=250, verbose_name='О себе'),
        ),
    ]
