# Generated by Django 2.2.16 on 2022-02-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.CharField(blank=True, default='Автор еще не заполнил этот раздел', max_length=250, verbose_name='О себе'),
        ),
    ]
